### PR TITLE
Changed rect and circle structs

### PR DESCRIPTION
**Pull request by EimaMei**
Changed the first 2 values being XY values, not size values because it's kinda dumb having the size as the 1st value and not the position

### CODE REVIEW

**Comment by ColleagueRiley** [comment]
no, lel

**Comment by ColleagueRiley** [comment]
the modern version already has this and will be commited in later

**Comment by EimaMei** [comment]
wdym modern? development branch? If so, I didn't see the fix

**Comment by ColleagueRiley** [comment]
My copy has this fix, it'll be commited in along with other fixes

**Comment by EimaMei** [comment]
pog

**Pull request closed without merging**
